version: '3'

services:
  honeybadgermpc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    command: pytest -v --cov=honeybadgermpc
    extra_hosts:
      - "hbmpc_0:127.0.0.1"
      - "hbmpc_1:127.0.0.1"
      - "hbmpc_2:127.0.0.1"
      - "hbmpc_3:127.0.0.1"
  builddocs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      - O=-W --keep-going
    command: make -C docs html
  viewdocs:
    image: nginx
    ports:
      - '58888:80'
    volumes:
      - ./docs/_build/html:/usr/share/nginx/html
